### ISSUE TITLE
Release bar file

### ISSUE THREAD

**Issue by vaskas** [saprykin/nsrreader-bb10#4]
Hi Alexander,

Thanks heaps for developing NSR Reader back in the day! It remains to be one of the key BB10 apps and is still super useful.

Now that the BB AppWorld is being apparently shut down in Jan 2022 it would be great to keep and preserve the bar file. Would you mind sharing it or attaching it to the release in GitHub?

**Comment by saprykin** [comment]
Hi @vaskas,

I did the development of BB10 apps on my old laptop which I don't have anymore, and all compiled bar files were there. Unfortunately, I don't have IDE and SDK installed anymore. As far as I remember there is no way to download bar files separately after they have been submitted for release.

**Comment by vaskas** [comment]
Thank you for the response @saprykin - I imagined that the bar could have been gone in history. I have now built it and attached to  https://github.com/BerryTrucks/nsrreader-bb10/releases/tag/V_1_6_3 - hope that's OK with you. Thanks again for the great GPL licensed code!

**Comment by saprykin** [comment]
@vaskas No problems, thanks for building it ! Feel free to distribute or modify it.
